### PR TITLE
A name for the selection strategy added

### PR DESCRIPTION
**Pull request by egbomol**
This PR addresses Issue #144.

### CODE REVIEW

**Comment by d-stahl-ericsson** [comment]
What does this PR address? What is the rationale? Is there an Issue connected to it?

**Comment by egbomol** [comment]
Storing the Test Case Selection strategy name can be useful for the executors do differentiate the TERCs in a more efficient way. Emil Backmark suggested this change.

**Comment by d-stahl-ericsson** [comment]
There needs to be an Issue to hang this onto, then we can talk about whether that Issue should be fixed or not. Regardless, this change would mean a change in event version (1.1.0). In other words, a new schema file (1.1.0.json), updated version properties in the event examples, and an updated event version history.

**Comment by egbomol** [comment]
Is it possible to handle this as a change request and remain with Github pull request? It is not an error. 
In addition we may have more change proposals in the near future for this Eiffel event.

It's not fully clear for me how the new version is created. I mean in the EiffelTestExecutionRecipeCollectionCreatedEvent.md file's  
## Version History
chapter. 
In case of a new version what shall I write into the "Introduced in" column?

**Comment by d-stahl-ericsson** [comment]
Of course we stay within GitHub - we want full traceability within the GitHub repo :)

"Introduced in" should say "Current version" for the new 1.1.0 - this puts us in a state in between editions, so it's not (yet) part of any edition.

**Pull request closed without merging**
