### PR TITLE
I don't think we need to scream

### PR DESCRIPTION
**Pull request by e-backmark-ericsson**
I'd like _SHOULD_ to be changed to _should_, since I see no point in screaming in the documentation.

Also, a small typo was fixed.

### CODE REVIEW

**Comment by d-stahl-ericsson** [comment]
Where defining explicit rules, SHOULD, SHALL and MAY are consistently capitalized throughout the documentation to emphasize their role as key words. This is common convention in specifications, see e.g. https://tools.ietf.org/html/rfc2119

**Comment by d-stahl-ericsson** [comment]
... or at least they SHOULD be thus emphasized :)
(Sorry, I couldn't resist...)

**Comment by e-backmark-ericsson** [comment]
Ok, I'll not argue against that. It just feels weird, but I'll bury my axe.

Still the typo is there :)

**Comment by d-stahl-ericsson** [comment]
:+1:

**Pull request merged**
